name: Backend CI Workflow
on:
  workflow_call:
    inputs: # Input Parameters
      appName:
        description: 'Name of the Application - for which CI is triggered'
        required: true
        type: string
      branch:
        description: 'Name of the branch - to checkout code. By default, checkout will be from main branch'
        required: false
        type: string
        default: 'main'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    name: Build Application Docker Image, Scan and Push to Github Packages
    uses: ./.github/workflows/docker-build-and-push.yaml
    with:
      appName: ${{ inputs.appName }}
      branch: ${{ inputs.branch }}
    secrets: inherit
