name: Backend CI Workflow

on:
  workflow_call:
    inputs: # Input Parameters
      appName:
        description: 'Name of the Application - for which CI is triggered'
        required: true
        type: string

jobs:
  build:
    name: Run build
    uses: ./.github/workflows/build.yaml
    with:
      appName: ${{ inputs.appName }}
    secrets: inherit
